// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/citadel.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 29330110;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiCitadelAndroidDisconnect();

  Future<TunSetupDto> crateApiCitadelAndroidEstablish({required String link});

  Future<TunSetupDto> crateApiCitadelAndroidEstablishProfile({
    required String id,
  });

  Stream<VpnEventDto> crateApiCitadelAndroidRunDataPlane({required int fd});

  String crateApiCitadelCoreVersion();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<LinkSummaryDto> crateApiCitadelLinkSummaryDtoDefault();

  LinkSummaryDto crateApiCitadelParseLinkSummary({required String uri});

  void crateApiCitadelSetDataDir({required String dir});

  ProfileDto crateApiCitadelVaultAdd({
    required String name,
    required String uri,
  });

  Future<void> crateApiCitadelVaultChangePassword({
    required String old,
    required String new_,
  });

  Future<void> crateApiCitadelVaultCreate({required String passphrase});

  bool crateApiCitadelVaultExists();

  bool crateApiCitadelVaultIsUnlocked();

  List<ProfileDto> crateApiCitadelVaultList();

  void crateApiCitadelVaultLock();

  void crateApiCitadelVaultRemove({required String id});

  Future<void> crateApiCitadelVaultUnlock({required String passphrase});

  Stream<VpnEventDto> crateApiCitadelVpnConnect({required String link});

  Stream<VpnEventDto> crateApiCitadelVpnConnectProfile({required String id});

  void crateApiCitadelVpnDisconnect();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiCitadelAndroidDisconnect() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelAndroidDisconnectConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelAndroidDisconnectConstMeta =>
      const TaskConstMeta(debugName: "android_disconnect", argNames: []);

  @override
  Future<TunSetupDto> crateApiCitadelAndroidEstablish({required String link}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(link, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tun_setup_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCitadelAndroidEstablishConstMeta,
        argValues: [link],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelAndroidEstablishConstMeta =>
      const TaskConstMeta(debugName: "android_establish", argNames: ["link"]);

  @override
  Future<TunSetupDto> crateApiCitadelAndroidEstablishProfile({
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tun_setup_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCitadelAndroidEstablishProfileConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelAndroidEstablishProfileConstMeta =>
      const TaskConstMeta(
        debugName: "android_establish_profile",
        argNames: ["id"],
      );

  @override
  Stream<VpnEventDto> crateApiCitadelAndroidRunDataPlane({required int fd}) {
    final sink = RustStreamSink<VpnEventDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_i_32(fd, serializer);
            sse_encode_StreamSink_vpn_event_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 4,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiCitadelAndroidRunDataPlaneConstMeta,
          argValues: [fd, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiCitadelAndroidRunDataPlaneConstMeta =>
      const TaskConstMeta(
        debugName: "android_run_data_plane",
        argNames: ["fd", "sink"],
      );

  @override
  String crateApiCitadelCoreVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelCoreVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelCoreVersionConstMeta =>
      const TaskConstMeta(debugName: "core_version", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<LinkSummaryDto> crateApiCitadelLinkSummaryDtoDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_link_summary_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelLinkSummaryDtoDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelLinkSummaryDtoDefaultConstMeta =>
      const TaskConstMeta(debugName: "link_summary_dto_default", argNames: []);

  @override
  LinkSummaryDto crateApiCitadelParseLinkSummary({required String uri}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(uri, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_link_summary_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelParseLinkSummaryConstMeta,
        argValues: [uri],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelParseLinkSummaryConstMeta =>
      const TaskConstMeta(debugName: "parse_link_summary", argNames: ["uri"]);

  @override
  void crateApiCitadelSetDataDir({required String dir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelSetDataDirConstMeta,
        argValues: [dir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelSetDataDirConstMeta =>
      const TaskConstMeta(debugName: "set_data_dir", argNames: ["dir"]);

  @override
  ProfileDto crateApiCitadelVaultAdd({
    required String name,
    required String uri,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(uri, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_profile_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCitadelVaultAddConstMeta,
        argValues: [name, uri],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultAddConstMeta =>
      const TaskConstMeta(debugName: "vault_add", argNames: ["name", "uri"]);

  @override
  Future<void> crateApiCitadelVaultChangePassword({
    required String old,
    required String new_,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(old, serializer);
          sse_encode_String(new_, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCitadelVaultChangePasswordConstMeta,
        argValues: [old, new_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultChangePasswordConstMeta =>
      const TaskConstMeta(
        debugName: "vault_change_password",
        argNames: ["old", "new_"],
      );

  @override
  Future<void> crateApiCitadelVaultCreate({required String passphrase}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCitadelVaultCreateConstMeta,
        argValues: [passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultCreateConstMeta =>
      const TaskConstMeta(debugName: "vault_create", argNames: ["passphrase"]);

  @override
  bool crateApiCitadelVaultExists() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelVaultExistsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultExistsConstMeta =>
      const TaskConstMeta(debugName: "vault_exists", argNames: []);

  @override
  bool crateApiCitadelVaultIsUnlocked() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelVaultIsUnlockedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultIsUnlockedConstMeta =>
      const TaskConstMeta(debugName: "vault_is_unlocked", argNames: []);

  @override
  List<ProfileDto> crateApiCitadelVaultList() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_profile_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCitadelVaultListConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultListConstMeta =>
      const TaskConstMeta(debugName: "vault_list", argNames: []);

  @override
  void crateApiCitadelVaultLock() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelVaultLockConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultLockConstMeta =>
      const TaskConstMeta(debugName: "vault_lock", argNames: []);

  @override
  void crateApiCitadelVaultRemove({required String id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCitadelVaultRemoveConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultRemoveConstMeta =>
      const TaskConstMeta(debugName: "vault_remove", argNames: ["id"]);

  @override
  Future<void> crateApiCitadelVaultUnlock({required String passphrase}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCitadelVaultUnlockConstMeta,
        argValues: [passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultUnlockConstMeta =>
      const TaskConstMeta(debugName: "vault_unlock", argNames: ["passphrase"]);

  @override
  Stream<VpnEventDto> crateApiCitadelVpnConnect({required String link}) {
    final sink = RustStreamSink<VpnEventDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(link, serializer);
            sse_encode_StreamSink_vpn_event_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 20,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiCitadelVpnConnectConstMeta,
          argValues: [link, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiCitadelVpnConnectConstMeta =>
      const TaskConstMeta(debugName: "vpn_connect", argNames: ["link", "sink"]);

  @override
  Stream<VpnEventDto> crateApiCitadelVpnConnectProfile({required String id}) {
    final sink = RustStreamSink<VpnEventDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(id, serializer);
            sse_encode_StreamSink_vpn_event_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 21,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiCitadelVpnConnectProfileConstMeta,
          argValues: [id, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiCitadelVpnConnectProfileConstMeta =>
      const TaskConstMeta(
        debugName: "vpn_connect_profile",
        argNames: ["id", "sink"],
      );

  @override
  void crateApiCitadelVpnDisconnect() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelVpnDisconnectConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVpnDisconnectConstMeta =>
      const TaskConstMeta(debugName: "vpn_disconnect", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<VpnEventDto> dco_decode_StreamSink_vpn_event_dto_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  LinkSummaryDto dco_decode_link_summary_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return LinkSummaryDto(
      valid: dco_decode_bool(arr[0]),
      servers: dco_decode_String(arr[1]),
      serverName: dco_decode_String(arr[2]),
      kxSuite: dco_decode_String(arr[3]),
      hasPin: dco_decode_bool(arr[4]),
      hasPqAuth: dco_decode_bool(arr[5]),
      hasObfs: dco_decode_bool(arr[6]),
    );
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProfileDto> dco_decode_list_profile_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_profile_dto).toList();
  }

  @protected
  ProfileDto dco_decode_profile_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ProfileDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      servers: dco_decode_String(arr[2]),
      hasPin: dco_decode_bool(arr[3]),
      hasPqAuth: dco_decode_bool(arr[4]),
      hasObfs: dco_decode_bool(arr[5]),
      lastExit: dco_decode_String(arr[6]),
    );
  }

  @protected
  TunSetupDto dco_decode_tun_setup_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return TunSetupDto(
      addr: dco_decode_String(arr[0]),
      prefix: dco_decode_u_32(arr[1]),
      mtu: dco_decode_String(arr[2]),
      routes: dco_decode_String(arr[3]),
      dns: dco_decode_String(arr[4]),
      exit: dco_decode_String(arr[5]),
      transport: dco_decode_String(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VpnEventDto dco_decode_vpn_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return VpnEventDto(
      kind: dco_decode_String(arr[0]),
      state: dco_decode_String(arr[1]),
      exit: dco_decode_String(arr[2]),
      transport: dco_decode_String(arr[3]),
      cidr: dco_decode_String(arr[4]),
      error: dco_decode_String(arr[5]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<VpnEventDto> sse_decode_StreamSink_vpn_event_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  LinkSummaryDto sse_decode_link_summary_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_valid = sse_decode_bool(deserializer);
    var var_servers = sse_decode_String(deserializer);
    var var_serverName = sse_decode_String(deserializer);
    var var_kxSuite = sse_decode_String(deserializer);
    var var_hasPin = sse_decode_bool(deserializer);
    var var_hasPqAuth = sse_decode_bool(deserializer);
    var var_hasObfs = sse_decode_bool(deserializer);
    return LinkSummaryDto(
      valid: var_valid,
      servers: var_servers,
      serverName: var_serverName,
      kxSuite: var_kxSuite,
      hasPin: var_hasPin,
      hasPqAuth: var_hasPqAuth,
      hasObfs: var_hasObfs,
    );
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProfileDto> sse_decode_list_profile_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProfileDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_profile_dto(deserializer));
    }
    return ans_;
  }

  @protected
  ProfileDto sse_decode_profile_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_servers = sse_decode_String(deserializer);
    var var_hasPin = sse_decode_bool(deserializer);
    var var_hasPqAuth = sse_decode_bool(deserializer);
    var var_hasObfs = sse_decode_bool(deserializer);
    var var_lastExit = sse_decode_String(deserializer);
    return ProfileDto(
      id: var_id,
      name: var_name,
      servers: var_servers,
      hasPin: var_hasPin,
      hasPqAuth: var_hasPqAuth,
      hasObfs: var_hasObfs,
      lastExit: var_lastExit,
    );
  }

  @protected
  TunSetupDto sse_decode_tun_setup_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_addr = sse_decode_String(deserializer);
    var var_prefix = sse_decode_u_32(deserializer);
    var var_mtu = sse_decode_String(deserializer);
    var var_routes = sse_decode_String(deserializer);
    var var_dns = sse_decode_String(deserializer);
    var var_exit = sse_decode_String(deserializer);
    var var_transport = sse_decode_String(deserializer);
    return TunSetupDto(
      addr: var_addr,
      prefix: var_prefix,
      mtu: var_mtu,
      routes: var_routes,
      dns: var_dns,
      exit: var_exit,
      transport: var_transport,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VpnEventDto sse_decode_vpn_event_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_state = sse_decode_String(deserializer);
    var var_exit = sse_decode_String(deserializer);
    var var_transport = sse_decode_String(deserializer);
    var var_cidr = sse_decode_String(deserializer);
    var var_error = sse_decode_String(deserializer);
    return VpnEventDto(
      kind: var_kind,
      state: var_state,
      exit: var_exit,
      transport: var_transport,
      cidr: var_cidr,
      error: var_error,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_vpn_event_dto_Sse(
    RustStreamSink<VpnEventDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_vpn_event_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_link_summary_dto(
    LinkSummaryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.valid, serializer);
    sse_encode_String(self.servers, serializer);
    sse_encode_String(self.serverName, serializer);
    sse_encode_String(self.kxSuite, serializer);
    sse_encode_bool(self.hasPin, serializer);
    sse_encode_bool(self.hasPqAuth, serializer);
    sse_encode_bool(self.hasObfs, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_profile_dto(
    List<ProfileDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_profile_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_profile_dto(ProfileDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.servers, serializer);
    sse_encode_bool(self.hasPin, serializer);
    sse_encode_bool(self.hasPqAuth, serializer);
    sse_encode_bool(self.hasObfs, serializer);
    sse_encode_String(self.lastExit, serializer);
  }

  @protected
  void sse_encode_tun_setup_dto(TunSetupDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.addr, serializer);
    sse_encode_u_32(self.prefix, serializer);
    sse_encode_String(self.mtu, serializer);
    sse_encode_String(self.routes, serializer);
    sse_encode_String(self.dns, serializer);
    sse_encode_String(self.exit, serializer);
    sse_encode_String(self.transport, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_vpn_event_dto(VpnEventDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.state, serializer);
    sse_encode_String(self.exit, serializer);
    sse_encode_String(self.transport, serializer);
    sse_encode_String(self.cidr, serializer);
    sse_encode_String(self.error, serializer);
  }
}
