// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/admin.dart';
import 'api/citadel.dart';
import 'api/diag.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1849053047;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<IssuedLinkDto> crateApiAdminAdminIssueSubscriber({
    required String profileId,
    required String label,
    required String validUntil,
  });

  Future<void> crateApiAdminAdminRevokeSubscriber({
    required String profileId,
    required String clientIdHex,
  });

  Future<List<SubscriberDto>> crateApiAdminAdminSubscribers({
    required String profileId,
  });

  Stream<VpnEventDto> crateApiCitadelAndroidAttachEvents();

  AndroidStatusDto crateApiCitadelAndroidSessionStatus();

  Stream<VpnEventDto> crateApiCitadelAndroidStartSession({
    required String link,
  });

  Stream<VpnEventDto> crateApiCitadelAndroidStartSessionProfile({
    required String id,
  });

  void crateApiCitadelAndroidStopSession();

  String crateApiCitadelCoreVersion();

  bool crateApiCitadelDebugEnabledPersisted();

  void crateApiDiagDebugLogClear();

  List<String> crateApiDiagDebugLogSnapshot();

  Stream<String> crateApiDiagDebugLogStream();

  void crateApiCitadelDesktopExitNow();

  void crateApiCitadelDesktopServiceQuit();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  bool crateApiCitadelKillswitchEnabled();

  QrDto crateApiCitadelLinkQr({required String uri});

  Future<LinkSummaryDto> crateApiCitadelLinkSummaryDtoDefault();

  Future<LinkSummaryDto> crateApiCitadelParseLinkSummary({required String uri});

  Stream<DiagLineDto> crateApiCitadelRunDiagnostics({
    String? profileId,
    String? link,
  });

  bool crateApiCitadelScreenshotBlockEnabled();

  void crateApiCitadelSetDataDir({required String dir});

  void crateApiCitadelSetDebugEnabled({required bool on_});

  void crateApiCitadelSetKillswitch({required bool on_});

  void crateApiDiagSetLogFile({required String path});

  void crateApiCitadelSetScreenshotBlock({required bool on_});

  void crateApiCitadelSetSplitConfig({required SplitTunnelDto cfg});

  SplitTunnelDto crateApiCitadelSplitConfig();

  void crateApiDiagStartLogCapture();

  Future<ProfileDto> crateApiCitadelVaultAdd({
    required String name,
    required String uri,
  });

  Future<void> crateApiCitadelVaultChangePassword({
    required String old,
    required String new_,
  });

  Future<void> crateApiCitadelVaultCreate({required String passphrase});

  bool crateApiCitadelVaultExists();

  bool crateApiCitadelVaultIsUnlocked();

  List<ProfileDto> crateApiCitadelVaultList();

  String crateApiCitadelVaultLocation();

  void crateApiCitadelVaultLock();

  int crateApiCitadelVaultMaxNameLen();

  int crateApiCitadelVaultMinPasswordLen();

  void crateApiCitadelVaultMove({required String id, required bool up});

  void crateApiCitadelVaultRemove({required String id});

  void crateApiCitadelVaultRename({required String id, required String name});

  Future<void> crateApiCitadelVaultUnlock({required String passphrase});

  Stream<VpnEventDto> crateApiCitadelVpnConnect({required String link});

  Stream<VpnEventDto> crateApiCitadelVpnConnectProfile({required String id});

  void crateApiCitadelVpnDisconnect();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<IssuedLinkDto> crateApiAdminAdminIssueSubscriber({
    required String profileId,
    required String label,
    required String validUntil,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(profileId, serializer);
          sse_encode_String(label, serializer);
          sse_encode_String(validUntil, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_issued_link_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAdminAdminIssueSubscriberConstMeta,
        argValues: [profileId, label, validUntil],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAdminAdminIssueSubscriberConstMeta =>
      const TaskConstMeta(
        debugName: "admin_issue_subscriber",
        argNames: ["profileId", "label", "validUntil"],
      );

  @override
  Future<void> crateApiAdminAdminRevokeSubscriber({
    required String profileId,
    required String clientIdHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(profileId, serializer);
          sse_encode_String(clientIdHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAdminAdminRevokeSubscriberConstMeta,
        argValues: [profileId, clientIdHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAdminAdminRevokeSubscriberConstMeta =>
      const TaskConstMeta(
        debugName: "admin_revoke_subscriber",
        argNames: ["profileId", "clientIdHex"],
      );

  @override
  Future<List<SubscriberDto>> crateApiAdminAdminSubscribers({
    required String profileId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(profileId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_subscriber_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAdminAdminSubscribersConstMeta,
        argValues: [profileId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAdminAdminSubscribersConstMeta =>
      const TaskConstMeta(
        debugName: "admin_subscribers",
        argNames: ["profileId"],
      );

  @override
  Stream<VpnEventDto> crateApiCitadelAndroidAttachEvents() {
    final sink = RustStreamSink<VpnEventDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_vpn_event_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 4,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiCitadelAndroidAttachEventsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiCitadelAndroidAttachEventsConstMeta =>
      const TaskConstMeta(
        debugName: "android_attach_events",
        argNames: ["sink"],
      );

  @override
  AndroidStatusDto crateApiCitadelAndroidSessionStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_android_status_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelAndroidSessionStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelAndroidSessionStatusConstMeta =>
      const TaskConstMeta(debugName: "android_session_status", argNames: []);

  @override
  Stream<VpnEventDto> crateApiCitadelAndroidStartSession({
    required String link,
  }) {
    final sink = RustStreamSink<VpnEventDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(link, serializer);
            sse_encode_StreamSink_vpn_event_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 6,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiCitadelAndroidStartSessionConstMeta,
          argValues: [link, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiCitadelAndroidStartSessionConstMeta =>
      const TaskConstMeta(
        debugName: "android_start_session",
        argNames: ["link", "sink"],
      );

  @override
  Stream<VpnEventDto> crateApiCitadelAndroidStartSessionProfile({
    required String id,
  }) {
    final sink = RustStreamSink<VpnEventDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(id, serializer);
            sse_encode_StreamSink_vpn_event_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 7,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiCitadelAndroidStartSessionProfileConstMeta,
          argValues: [id, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiCitadelAndroidStartSessionProfileConstMeta =>
      const TaskConstMeta(
        debugName: "android_start_session_profile",
        argNames: ["id", "sink"],
      );

  @override
  void crateApiCitadelAndroidStopSession() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelAndroidStopSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelAndroidStopSessionConstMeta =>
      const TaskConstMeta(debugName: "android_stop_session", argNames: []);

  @override
  String crateApiCitadelCoreVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelCoreVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelCoreVersionConstMeta =>
      const TaskConstMeta(debugName: "core_version", argNames: []);

  @override
  bool crateApiCitadelDebugEnabledPersisted() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelDebugEnabledPersistedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelDebugEnabledPersistedConstMeta =>
      const TaskConstMeta(debugName: "debug_enabled_persisted", argNames: []);

  @override
  void crateApiDiagDebugLogClear() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDiagDebugLogClearConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiagDebugLogClearConstMeta =>
      const TaskConstMeta(debugName: "debug_log_clear", argNames: []);

  @override
  List<String> crateApiDiagDebugLogSnapshot() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDiagDebugLogSnapshotConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiagDebugLogSnapshotConstMeta =>
      const TaskConstMeta(debugName: "debug_log_snapshot", argNames: []);

  @override
  Stream<String> crateApiDiagDebugLogStream() {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 13,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiDiagDebugLogStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDiagDebugLogStreamConstMeta =>
      const TaskConstMeta(debugName: "debug_log_stream", argNames: ["sink"]);

  @override
  void crateApiCitadelDesktopExitNow() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelDesktopExitNowConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelDesktopExitNowConstMeta =>
      const TaskConstMeta(debugName: "desktop_exit_now", argNames: []);

  @override
  void crateApiCitadelDesktopServiceQuit() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelDesktopServiceQuitConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelDesktopServiceQuitConstMeta =>
      const TaskConstMeta(debugName: "desktop_service_quit", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiCitadelKillswitchEnabled() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelKillswitchEnabledConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelKillswitchEnabledConstMeta =>
      const TaskConstMeta(debugName: "killswitch_enabled", argNames: []);

  @override
  QrDto crateApiCitadelLinkQr({required String uri}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(uri, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qr_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCitadelLinkQrConstMeta,
        argValues: [uri],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelLinkQrConstMeta =>
      const TaskConstMeta(debugName: "link_qr", argNames: ["uri"]);

  @override
  Future<LinkSummaryDto> crateApiCitadelLinkSummaryDtoDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_link_summary_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelLinkSummaryDtoDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelLinkSummaryDtoDefaultConstMeta =>
      const TaskConstMeta(debugName: "link_summary_dto_default", argNames: []);

  @override
  Future<LinkSummaryDto> crateApiCitadelParseLinkSummary({
    required String uri,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(uri, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_link_summary_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelParseLinkSummaryConstMeta,
        argValues: [uri],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelParseLinkSummaryConstMeta =>
      const TaskConstMeta(debugName: "parse_link_summary", argNames: ["uri"]);

  @override
  Stream<DiagLineDto> crateApiCitadelRunDiagnostics({
    String? profileId,
    String? link,
  }) {
    final sink = RustStreamSink<DiagLineDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_opt_String(profileId, serializer);
            sse_encode_opt_String(link, serializer);
            sse_encode_StreamSink_diag_line_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 22,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiCitadelRunDiagnosticsConstMeta,
          argValues: [profileId, link, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiCitadelRunDiagnosticsConstMeta =>
      const TaskConstMeta(
        debugName: "run_diagnostics",
        argNames: ["profileId", "link", "sink"],
      );

  @override
  bool crateApiCitadelScreenshotBlockEnabled() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelScreenshotBlockEnabledConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelScreenshotBlockEnabledConstMeta =>
      const TaskConstMeta(debugName: "screenshot_block_enabled", argNames: []);

  @override
  void crateApiCitadelSetDataDir({required String dir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelSetDataDirConstMeta,
        argValues: [dir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelSetDataDirConstMeta =>
      const TaskConstMeta(debugName: "set_data_dir", argNames: ["dir"]);

  @override
  void crateApiCitadelSetDebugEnabled({required bool on_}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(on_, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelSetDebugEnabledConstMeta,
        argValues: [on_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelSetDebugEnabledConstMeta =>
      const TaskConstMeta(debugName: "set_debug_enabled", argNames: ["on_"]);

  @override
  void crateApiCitadelSetKillswitch({required bool on_}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(on_, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelSetKillswitchConstMeta,
        argValues: [on_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelSetKillswitchConstMeta =>
      const TaskConstMeta(debugName: "set_killswitch", argNames: ["on_"]);

  @override
  void crateApiDiagSetLogFile({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDiagSetLogFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiagSetLogFileConstMeta =>
      const TaskConstMeta(debugName: "set_log_file", argNames: ["path"]);

  @override
  void crateApiCitadelSetScreenshotBlock({required bool on_}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(on_, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelSetScreenshotBlockConstMeta,
        argValues: [on_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelSetScreenshotBlockConstMeta =>
      const TaskConstMeta(debugName: "set_screenshot_block", argNames: ["on_"]);

  @override
  void crateApiCitadelSetSplitConfig({required SplitTunnelDto cfg}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_split_tunnel_dto(cfg, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelSetSplitConfigConstMeta,
        argValues: [cfg],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelSetSplitConfigConstMeta =>
      const TaskConstMeta(debugName: "set_split_config", argNames: ["cfg"]);

  @override
  SplitTunnelDto crateApiCitadelSplitConfig() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_split_tunnel_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelSplitConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelSplitConfigConstMeta =>
      const TaskConstMeta(debugName: "split_config", argNames: []);

  @override
  void crateApiDiagStartLogCapture() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDiagStartLogCaptureConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiagStartLogCaptureConstMeta =>
      const TaskConstMeta(debugName: "start_log_capture", argNames: []);

  @override
  Future<ProfileDto> crateApiCitadelVaultAdd({
    required String name,
    required String uri,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(uri, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_profile_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCitadelVaultAddConstMeta,
        argValues: [name, uri],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultAddConstMeta =>
      const TaskConstMeta(debugName: "vault_add", argNames: ["name", "uri"]);

  @override
  Future<void> crateApiCitadelVaultChangePassword({
    required String old,
    required String new_,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(old, serializer);
          sse_encode_String(new_, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCitadelVaultChangePasswordConstMeta,
        argValues: [old, new_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultChangePasswordConstMeta =>
      const TaskConstMeta(
        debugName: "vault_change_password",
        argNames: ["old", "new_"],
      );

  @override
  Future<void> crateApiCitadelVaultCreate({required String passphrase}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCitadelVaultCreateConstMeta,
        argValues: [passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultCreateConstMeta =>
      const TaskConstMeta(debugName: "vault_create", argNames: ["passphrase"]);

  @override
  bool crateApiCitadelVaultExists() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 35)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelVaultExistsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultExistsConstMeta =>
      const TaskConstMeta(debugName: "vault_exists", argNames: []);

  @override
  bool crateApiCitadelVaultIsUnlocked() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelVaultIsUnlockedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultIsUnlockedConstMeta =>
      const TaskConstMeta(debugName: "vault_is_unlocked", argNames: []);

  @override
  List<ProfileDto> crateApiCitadelVaultList() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 37)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_profile_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCitadelVaultListConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultListConstMeta =>
      const TaskConstMeta(debugName: "vault_list", argNames: []);

  @override
  String crateApiCitadelVaultLocation() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 38)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelVaultLocationConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultLocationConstMeta =>
      const TaskConstMeta(debugName: "vault_location", argNames: []);

  @override
  void crateApiCitadelVaultLock() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 39)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelVaultLockConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultLockConstMeta =>
      const TaskConstMeta(debugName: "vault_lock", argNames: []);

  @override
  int crateApiCitadelVaultMaxNameLen() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 40)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelVaultMaxNameLenConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultMaxNameLenConstMeta =>
      const TaskConstMeta(debugName: "vault_max_name_len", argNames: []);

  @override
  int crateApiCitadelVaultMinPasswordLen() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 41)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelVaultMinPasswordLenConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultMinPasswordLenConstMeta =>
      const TaskConstMeta(debugName: "vault_min_password_len", argNames: []);

  @override
  void crateApiCitadelVaultMove({required String id, required bool up}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_bool(up, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 42)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCitadelVaultMoveConstMeta,
        argValues: [id, up],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultMoveConstMeta =>
      const TaskConstMeta(debugName: "vault_move", argNames: ["id", "up"]);

  @override
  void crateApiCitadelVaultRemove({required String id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 43)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCitadelVaultRemoveConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultRemoveConstMeta =>
      const TaskConstMeta(debugName: "vault_remove", argNames: ["id"]);

  @override
  void crateApiCitadelVaultRename({required String id, required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 44)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCitadelVaultRenameConstMeta,
        argValues: [id, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultRenameConstMeta =>
      const TaskConstMeta(debugName: "vault_rename", argNames: ["id", "name"]);

  @override
  Future<void> crateApiCitadelVaultUnlock({required String passphrase}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 45,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCitadelVaultUnlockConstMeta,
        argValues: [passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVaultUnlockConstMeta =>
      const TaskConstMeta(debugName: "vault_unlock", argNames: ["passphrase"]);

  @override
  Stream<VpnEventDto> crateApiCitadelVpnConnect({required String link}) {
    final sink = RustStreamSink<VpnEventDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(link, serializer);
            sse_encode_StreamSink_vpn_event_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 46,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiCitadelVpnConnectConstMeta,
          argValues: [link, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiCitadelVpnConnectConstMeta =>
      const TaskConstMeta(debugName: "vpn_connect", argNames: ["link", "sink"]);

  @override
  Stream<VpnEventDto> crateApiCitadelVpnConnectProfile({required String id}) {
    final sink = RustStreamSink<VpnEventDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(id, serializer);
            sse_encode_StreamSink_vpn_event_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 47,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiCitadelVpnConnectProfileConstMeta,
          argValues: [id, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiCitadelVpnConnectProfileConstMeta =>
      const TaskConstMeta(
        debugName: "vpn_connect_profile",
        argNames: ["id", "sink"],
      );

  @override
  void crateApiCitadelVpnDisconnect() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 48)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCitadelVpnDisconnectConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCitadelVpnDisconnectConstMeta =>
      const TaskConstMeta(debugName: "vpn_disconnect", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<DiagLineDto> dco_decode_StreamSink_diag_line_dto_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<VpnEventDto> dco_decode_StreamSink_vpn_event_dto_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AndroidStatusDto dco_decode_android_status_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AndroidStatusDto(
      state: dco_decode_String(arr[0]),
      exit: dco_decode_String(arr[1]),
      transport: dco_decode_String(arr[2]),
      cidr: dco_decode_String(arr[3]),
      profileId: dco_decode_String(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  SplitTunnelDto dco_decode_box_autoadd_split_tunnel_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_split_tunnel_dto(raw);
  }

  @protected
  DiagLineDto dco_decode_diag_line_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DiagLineDto(
      step: dco_decode_String(arr[0]),
      ok: dco_decode_bool(arr[1]),
      detail: dco_decode_String(arr[2]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  IssuedLinkDto dco_decode_issued_link_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return IssuedLinkDto(
      clientIdHex: dco_decode_String(arr[0]),
      uri: dco_decode_String(arr[1]),
    );
  }

  @protected
  LinkSummaryDto dco_decode_link_summary_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return LinkSummaryDto(
      valid: dco_decode_bool(arr[0]),
      servers: dco_decode_String(arr[1]),
      serverName: dco_decode_String(arr[2]),
      kxSuite: dco_decode_String(arr[3]),
      hasPin: dco_decode_bool(arr[4]),
      hasPqAuth: dco_decode_bool(arr[5]),
      hasObfs: dco_decode_bool(arr[6]),
      isAdmin: dco_decode_bool(arr[7]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProfileDto> dco_decode_list_profile_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_profile_dto).toList();
  }

  @protected
  List<SubscriberDto> dco_decode_list_subscriber_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_subscriber_dto).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ProfileDto dco_decode_profile_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ProfileDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      servers: dco_decode_String(arr[2]),
      hasPin: dco_decode_bool(arr[3]),
      hasPqAuth: dco_decode_bool(arr[4]),
      hasObfs: dco_decode_bool(arr[5]),
      isAdmin: dco_decode_bool(arr[6]),
      lastExit: dco_decode_String(arr[7]),
    );
  }

  @protected
  QrDto dco_decode_qr_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return QrDto(
      size: dco_decode_u_32(arr[0]),
      cells: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  SplitTunnelDto dco_decode_split_tunnel_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SplitTunnelDto(
      appMode: dco_decode_String(arr[0]),
      apps: dco_decode_list_String(arr[1]),
      destMode: dco_decode_String(arr[2]),
      dests: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  SubscriberDto dco_decode_subscriber_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SubscriberDto(
      clientIdHex: dco_decode_String(arr[0]),
      validUntilUnix: dco_decode_i_64(arr[1]),
      status: dco_decode_String(arr[2]),
      active: dco_decode_bool(arr[3]),
      label: dco_decode_String(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VpnEventDto dco_decode_vpn_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return VpnEventDto(
      kind: dco_decode_String(arr[0]),
      state: dco_decode_String(arr[1]),
      exit: dco_decode_String(arr[2]),
      transport: dco_decode_String(arr[3]),
      cidr: dco_decode_String(arr[4]),
      error: dco_decode_String(arr[5]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<DiagLineDto> sse_decode_StreamSink_diag_line_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<VpnEventDto> sse_decode_StreamSink_vpn_event_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AndroidStatusDto sse_decode_android_status_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_state = sse_decode_String(deserializer);
    var var_exit = sse_decode_String(deserializer);
    var var_transport = sse_decode_String(deserializer);
    var var_cidr = sse_decode_String(deserializer);
    var var_profileId = sse_decode_String(deserializer);
    return AndroidStatusDto(
      state: var_state,
      exit: var_exit,
      transport: var_transport,
      cidr: var_cidr,
      profileId: var_profileId,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  SplitTunnelDto sse_decode_box_autoadd_split_tunnel_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_split_tunnel_dto(deserializer));
  }

  @protected
  DiagLineDto sse_decode_diag_line_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_step = sse_decode_String(deserializer);
    var var_ok = sse_decode_bool(deserializer);
    var var_detail = sse_decode_String(deserializer);
    return DiagLineDto(step: var_step, ok: var_ok, detail: var_detail);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  IssuedLinkDto sse_decode_issued_link_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_clientIdHex = sse_decode_String(deserializer);
    var var_uri = sse_decode_String(deserializer);
    return IssuedLinkDto(clientIdHex: var_clientIdHex, uri: var_uri);
  }

  @protected
  LinkSummaryDto sse_decode_link_summary_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_valid = sse_decode_bool(deserializer);
    var var_servers = sse_decode_String(deserializer);
    var var_serverName = sse_decode_String(deserializer);
    var var_kxSuite = sse_decode_String(deserializer);
    var var_hasPin = sse_decode_bool(deserializer);
    var var_hasPqAuth = sse_decode_bool(deserializer);
    var var_hasObfs = sse_decode_bool(deserializer);
    var var_isAdmin = sse_decode_bool(deserializer);
    return LinkSummaryDto(
      valid: var_valid,
      servers: var_servers,
      serverName: var_serverName,
      kxSuite: var_kxSuite,
      hasPin: var_hasPin,
      hasPqAuth: var_hasPqAuth,
      hasObfs: var_hasObfs,
      isAdmin: var_isAdmin,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProfileDto> sse_decode_list_profile_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProfileDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_profile_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<SubscriberDto> sse_decode_list_subscriber_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SubscriberDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_subscriber_dto(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProfileDto sse_decode_profile_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_servers = sse_decode_String(deserializer);
    var var_hasPin = sse_decode_bool(deserializer);
    var var_hasPqAuth = sse_decode_bool(deserializer);
    var var_hasObfs = sse_decode_bool(deserializer);
    var var_isAdmin = sse_decode_bool(deserializer);
    var var_lastExit = sse_decode_String(deserializer);
    return ProfileDto(
      id: var_id,
      name: var_name,
      servers: var_servers,
      hasPin: var_hasPin,
      hasPqAuth: var_hasPqAuth,
      hasObfs: var_hasObfs,
      isAdmin: var_isAdmin,
      lastExit: var_lastExit,
    );
  }

  @protected
  QrDto sse_decode_qr_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_size = sse_decode_u_32(deserializer);
    var var_cells = sse_decode_list_prim_u_8_strict(deserializer);
    return QrDto(size: var_size, cells: var_cells);
  }

  @protected
  SplitTunnelDto sse_decode_split_tunnel_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_appMode = sse_decode_String(deserializer);
    var var_apps = sse_decode_list_String(deserializer);
    var var_destMode = sse_decode_String(deserializer);
    var var_dests = sse_decode_list_String(deserializer);
    return SplitTunnelDto(
      appMode: var_appMode,
      apps: var_apps,
      destMode: var_destMode,
      dests: var_dests,
    );
  }

  @protected
  SubscriberDto sse_decode_subscriber_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_clientIdHex = sse_decode_String(deserializer);
    var var_validUntilUnix = sse_decode_i_64(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_active = sse_decode_bool(deserializer);
    var var_label = sse_decode_String(deserializer);
    return SubscriberDto(
      clientIdHex: var_clientIdHex,
      validUntilUnix: var_validUntilUnix,
      status: var_status,
      active: var_active,
      label: var_label,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VpnEventDto sse_decode_vpn_event_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_state = sse_decode_String(deserializer);
    var var_exit = sse_decode_String(deserializer);
    var var_transport = sse_decode_String(deserializer);
    var var_cidr = sse_decode_String(deserializer);
    var var_error = sse_decode_String(deserializer);
    return VpnEventDto(
      kind: var_kind,
      state: var_state,
      exit: var_exit,
      transport: var_transport,
      cidr: var_cidr,
      error: var_error,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_diag_line_dto_Sse(
    RustStreamSink<DiagLineDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_diag_line_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_vpn_event_dto_Sse(
    RustStreamSink<VpnEventDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_vpn_event_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_android_status_dto(
    AndroidStatusDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.state, serializer);
    sse_encode_String(self.exit, serializer);
    sse_encode_String(self.transport, serializer);
    sse_encode_String(self.cidr, serializer);
    sse_encode_String(self.profileId, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_split_tunnel_dto(
    SplitTunnelDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_split_tunnel_dto(self, serializer);
  }

  @protected
  void sse_encode_diag_line_dto(DiagLineDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.step, serializer);
    sse_encode_bool(self.ok, serializer);
    sse_encode_String(self.detail, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_issued_link_dto(
    IssuedLinkDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.clientIdHex, serializer);
    sse_encode_String(self.uri, serializer);
  }

  @protected
  void sse_encode_link_summary_dto(
    LinkSummaryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.valid, serializer);
    sse_encode_String(self.servers, serializer);
    sse_encode_String(self.serverName, serializer);
    sse_encode_String(self.kxSuite, serializer);
    sse_encode_bool(self.hasPin, serializer);
    sse_encode_bool(self.hasPqAuth, serializer);
    sse_encode_bool(self.hasObfs, serializer);
    sse_encode_bool(self.isAdmin, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_profile_dto(
    List<ProfileDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_profile_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_subscriber_dto(
    List<SubscriberDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_subscriber_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_profile_dto(ProfileDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.servers, serializer);
    sse_encode_bool(self.hasPin, serializer);
    sse_encode_bool(self.hasPqAuth, serializer);
    sse_encode_bool(self.hasObfs, serializer);
    sse_encode_bool(self.isAdmin, serializer);
    sse_encode_String(self.lastExit, serializer);
  }

  @protected
  void sse_encode_qr_dto(QrDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.size, serializer);
    sse_encode_list_prim_u_8_strict(self.cells, serializer);
  }

  @protected
  void sse_encode_split_tunnel_dto(
    SplitTunnelDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.appMode, serializer);
    sse_encode_list_String(self.apps, serializer);
    sse_encode_String(self.destMode, serializer);
    sse_encode_list_String(self.dests, serializer);
  }

  @protected
  void sse_encode_subscriber_dto(SubscriberDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.clientIdHex, serializer);
    sse_encode_i_64(self.validUntilUnix, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_bool(self.active, serializer);
    sse_encode_String(self.label, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_vpn_event_dto(VpnEventDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.state, serializer);
    sse_encode_String(self.exit, serializer);
    sse_encode_String(self.transport, serializer);
    sse_encode_String(self.cidr, serializer);
    sse_encode_String(self.error, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
