// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Список абонентов реестра развёрнутого сервера (SSH → `citadel-token registry list`).
Future<List<RegistryEntryDto>> adminRegistryList({required AdminConn conn}) =>
    RustLib.instance.api.crateApiAdminAdminRegistryList(conn: conn);

/// Зарегистрировать абонента. `client_id` — Ed25519 pub (64 hex). `valid_until` — `+<N>d`/`+<N>h`/
/// unix-секунды или пусто (дефолт +365d на сервере). Ввод валидируется в ядре (анти-инъекция).
Future<void> adminRegistryAdd({
  required AdminConn conn,
  required String clientId,
  required String validUntil,
}) => RustLib.instance.api.crateApiAdminAdminRegistryAdd(
  conn: conn,
  clientId: clientId,
  validUntil: validUntil,
);

/// Отозвать абонента по `client_id` (status=revoked; действует ≤ длины эпохи).
Future<void> adminRegistryRevoke({
  required AdminConn conn,
  required String clientId,
}) => RustLib.instance.api.crateApiAdminAdminRegistryRevoke(
  conn: conn,
  clientId: clientId,
);

/// Параметры SSH-подключения к серверу для Admin-операций.
class AdminConn {
  final String host;
  final int port;
  final String user;

  /// Пароль (используется, если `key_path` пуст).
  final String password;

  /// Путь к приватному SSH-ключу (OpenSSH-PEM). Не пуст → key-auth вместо пароля. Ключ читается
  /// в ядре, в Dart не передаётся.
  final String keyPath;

  /// Passphrase ключа (пусто → без passphrase).
  final String keyPassphrase;

  const AdminConn({
    required this.host,
    required this.port,
    required this.user,
    required this.password,
    required this.keyPath,
    required this.keyPassphrase,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      port.hashCode ^
      user.hashCode ^
      password.hashCode ^
      keyPath.hashCode ^
      keyPassphrase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdminConn &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          user == other.user &&
          password == other.password &&
          keyPath == other.keyPath &&
          keyPassphrase == other.keyPassphrase;
}

/// Запись Layer-1 реестра для Admin-UI.
class RegistryEntryDto {
  /// client_id абонента (Ed25519 pub, 64 hex).
  final String clientId;

  /// Срок действия (unix-секунды).
  final PlatformInt64 validUntilUnix;

  /// Статус строки реестра как есть (`active`|`revoked`|…).
  final String status;

  /// Удобный флаг для UI: строка активна (`status == "active"`).
  final bool active;

  const RegistryEntryDto({
    required this.clientId,
    required this.validUntilUnix,
    required this.status,
    required this.active,
  });

  @override
  int get hashCode =>
      clientId.hashCode ^
      validUntilUnix.hashCode ^
      status.hashCode ^
      active.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RegistryEntryDto &&
          runtimeType == other.runtimeType &&
          clientId == other.clientId &&
          validUntilUnix == other.validUntilUnix &&
          status == other.status &&
          active == other.active;
}
