// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Список абонентов реестра сервера admin-профиля (по туннелю), с локальными метками.
/// Требует разблокированного vault; канал достижим только при поднятой сессии этого профиля.
Future<List<SubscriberDto>> adminSubscribers({required String profileId}) =>
    RustLib.instance.api.crateApiAdminAdminSubscribers(profileId: profileId);

/// Выдать доступ новому абоненту: свежий seed → регистрация pub по каналу → клиентская ссылка
/// (собирается локально, issuer seed не видит — модель C5.4b). `valid_until`: пусто → серверный
/// дефолт (+365d), `+30d`/`+12h`/unix-секунды. `label` — локальная метка (только vault админа).
Future<IssuedLinkDto> adminIssueSubscriber({
  required String profileId,
  required String label,
  required String validUntil,
}) => RustLib.instance.api.crateApiAdminAdminIssueSubscriber(
  profileId: profileId,
  label: label,
  validUntil: validUntil,
);

/// Отозвать абонента по client_id (status=revoked; действует ≤ длины эпохи). Отзыв собственного
/// admin client_id сервер отклонит (анти-self-lockout, R6). Метку в vault НЕ удаляем — «кому был
/// выдан отозванный id» остаётся видно в списке.
Future<void> adminRevokeSubscriber({
  required String profileId,
  required String clientIdHex,
}) => RustLib.instance.api.crateApiAdminAdminRevokeSubscriber(
  profileId: profileId,
  clientIdHex: clientIdHex,
);

/// Результат выдачи доступа: client_id + готовая КЛИЕНТСКАЯ ссылка (без admin-полей).
/// `uri` показывается один раз (QR/копирование) — seed абонента у админа НЕ сохраняется.
class IssuedLinkDto {
  final String clientIdHex;
  final String uri;

  const IssuedLinkDto({required this.clientIdHex, required this.uri});

  @override
  int get hashCode => clientIdHex.hashCode ^ uri.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IssuedLinkDto &&
          runtimeType == other.runtimeType &&
          clientIdHex == other.clientIdHex &&
          uri == other.uri;
}

/// Абонент Layer-1 реестра для UI: серверная запись + локальная метка админа.
class SubscriberDto {
  /// client_id абонента (Ed25519 pub, 64 hex).
  final String clientIdHex;

  /// Срок действия (unix-секунды).
  final PlatformInt64 validUntilUnix;

  /// Статус строки реестра как есть (`active`|`revoked`|…).
  final String status;

  /// Удобный флаг для UI: строка активна (`status == "active"`).
  final bool active;

  /// Метка админа из vault («телефон Али»); пусто — если не сохранена (выдан вне этого устройства).
  final String label;

  const SubscriberDto({
    required this.clientIdHex,
    required this.validUntilUnix,
    required this.status,
    required this.active,
    required this.label,
  });

  @override
  int get hashCode =>
      clientIdHex.hashCode ^
      validUntilUnix.hashCode ^
      status.hashCode ^
      active.hashCode ^
      label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubscriberDto &&
          runtimeType == other.runtimeType &&
          clientIdHex == other.clientIdHex &&
          validUntilUnix == other.validUntilUnix &&
          status == other.status &&
          active == other.active &&
          label == other.label;
}
