// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Список абонентов реестра развёрнутого сервера (SSH → `citadel-token registry list`).
Future<List<RegistryEntryDto>> adminRegistryList({
  required String host,
  required int port,
  required String user,
  required String password,
}) => RustLib.instance.api.crateApiAdminAdminRegistryList(
  host: host,
  port: port,
  user: user,
  password: password,
);

/// Зарегистрировать абонента. `client_id` — Ed25519 pub (64 hex). `valid_until` — `+<N>d`/`+<N>h`/
/// unix-секунды или пусто (дефолт +365d на сервере). Ввод валидируется в ядре (анти-инъекция).
Future<void> adminRegistryAdd({
  required String host,
  required int port,
  required String user,
  required String password,
  required String clientId,
  required String validUntil,
}) => RustLib.instance.api.crateApiAdminAdminRegistryAdd(
  host: host,
  port: port,
  user: user,
  password: password,
  clientId: clientId,
  validUntil: validUntil,
);

/// Отозвать абонента по `client_id` (status=revoked; действует ≤ длины эпохи).
Future<void> adminRegistryRevoke({
  required String host,
  required int port,
  required String user,
  required String password,
  required String clientId,
}) => RustLib.instance.api.crateApiAdminAdminRegistryRevoke(
  host: host,
  port: port,
  user: user,
  password: password,
  clientId: clientId,
);

/// Запись Layer-1 реестра для Admin-UI.
class RegistryEntryDto {
  /// client_id абонента (Ed25519 pub, 64 hex).
  final String clientId;

  /// Срок действия (unix-секунды).
  final PlatformInt64 validUntilUnix;

  /// Статус строки реестра как есть (`active`|`revoked`|…).
  final String status;

  /// Удобный флаг для UI: строка активна (`status == "active"`).
  final bool active;

  const RegistryEntryDto({
    required this.clientId,
    required this.validUntilUnix,
    required this.status,
    required this.active,
  });

  @override
  int get hashCode =>
      clientId.hashCode ^
      validUntilUnix.hashCode ^
      status.hashCode ^
      active.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RegistryEntryDto &&
          runtimeType == other.runtimeType &&
          clientId == other.clientId &&
          validUntilUnix == other.validUntilUnix &&
          status == other.status &&
          active == other.active;
}
