// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `android_start`, `debug_flag_file`, `dto_to_split`, `first_line`, `guarded_parse_link`, `idle`, `io_kind_in_chain`, `is_not_found`, `is_permission_denied`, `killswitch_file`, `link_from`, `load_split_config`, `off`, `parse_split`, `profile_to_dto`, `profile_uri`, `read_error`, `rt`, `screenshot_block_file`, `serialize_split`, `spawn_controller`, `split_file`, `start_connect`, `state_dto`, `to_dto`, `update_android_status`, `update_last_exit`, `vault_error`, `vault_path`, `vpn_state_str`, `with_vault`, `write_error`, `xdg_store_path`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AndroidStatus`, `AndroidTunProvider`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `configure`

/// Версия PQ-VPN-ядра (about-экран).
String coreVersion() => RustLib.instance.api.crateApiCitadelCoreVersion();

/// Включить/выключить kill-switch (GUI-тумблер, desktop). Применяется со СЛЕДУЮЩЕГО подключения;
/// сохраняется на диск (переживает рестарт приложения).
void setKillswitch({required bool on_}) =>
    RustLib.instance.api.crateApiCitadelSetKillswitch(on_: on_);

/// Текущее состояние kill-switch (инициализация тумблера). Ленивая подгрузка сохранённого значения
/// при первом обращении — персист между запусками.
bool killswitchEnabled() =>
    RustLib.instance.api.crateApiCitadelKillswitchEnabled();

/// Сохранить настройку режима отладки (GUI-тумблер) на диск — переживает рестарт приложения.
void setDebugEnabled({required bool on_}) =>
    RustLib.instance.api.crateApiCitadelSetDebugEnabled(on_: on_);

/// Сохранённое состояние режима отладки (инициализация тумблера). Ленивая подгрузка при первом
/// обращении; файла нет → дефолт ВЫКЛЮЧЕН. Имя `*_persisted` — чтобы Dart-обёртка не конфликтовала
/// с полем `AppState.debugEnabled`.
bool debugEnabledPersisted() =>
    RustLib.instance.api.crateApiCitadelDebugEnabledPersisted();

/// Сохранить настройку запрета скриншотов (GUI-тумблер) — переживает рестарт.
void setScreenshotBlock({required bool on_}) =>
    RustLib.instance.api.crateApiCitadelSetScreenshotBlock(on_: on_);

/// Сохранённое состояние запрета скриншотов (инициализация тумблера/применения). Ленивая подгрузка;
/// файла нет → **дефолт true** (запрет включён). Только "0" в файле выключает.
bool screenshotBlockEnabled() =>
    RustLib.instance.api.crateApiCitadelScreenshotBlockEnabled();

/// Сохранить split-настройку (GUI). Применяется со СЛЕДУЮЩЕГО подключения; переживает рестарт.
void setSplitConfig({required SplitTunnelDto cfg}) =>
    RustLib.instance.api.crateApiCitadelSetSplitConfig(cfg: cfg);

/// Прочитать сохранённую split-настройку (инициализация GUI). Файла нет → всё "off".
SplitTunnelDto splitConfig() =>
    RustLib.instance.api.crateApiCitadelSplitConfig();

/// Задать каталог данных приложения (вызывается из Dart на старте, до любых vault-операций).
/// На Android — `getApplicationSupportDirectory()`; на десктопе можно не вызывать. Идемпотентно:
/// первый успешный вызов фиксирует путь (повторные молча игнорируются).
void setDataDir({required String dir}) =>
    RustLib.instance.api.crateApiCitadelSetDataDir(dir: dir);

/// Существует ли файл хранилища (UI: разблокировать vs первый запуск).
bool vaultExists() => RustLib.instance.api.crateApiCitadelVaultExists();

/// Разблокирован ли vault в текущей сессии приложения.
bool vaultIsUnlocked() => RustLib.instance.api.crateApiCitadelVaultIsUnlocked();

/// Заблокировать (забыть ключ из памяти).
void vaultLock() => RustLib.instance.api.crateApiCitadelVaultLock();

/// Где лежит файл хранилища (диагностика в UI: «нет доступа» без пути — бесполезное сообщение).
String vaultLocation() => RustLib.instance.api.crateApiCitadelVaultLocation();

/// Минимальная длина мастер-пароля из ядра — чтобы UI проверял ДО дорогого Argon2-derive и
/// называл человеку то же число, что enforce'ит крипта (без второй захардкоженной константы).
int vaultMinPasswordLen() =>
    RustLib.instance.api.crateApiCitadelVaultMinPasswordLen();

/// Открыть хранилище мастер-паролем (Argon2id — намеренно НЕ sync: тяжело, уводим с UI-потока).
/// Ошибка приходит в UI уже человеческой фразой (см. [`vault_error`]).
Future<void> vaultUnlock({required String passphrase}) =>
    RustLib.instance.api.crateApiCitadelVaultUnlock(passphrase: passphrase);

/// Создать новое хранилище под мастер-паролем (первый запуск / первое сохранение).
Future<void> vaultCreate({required String passphrase}) =>
    RustLib.instance.api.crateApiCitadelVaultCreate(passphrase: passphrase);

/// Сменить мастер-пароль. Три отказа — три РАЗНЫХ ответа, потому что чинятся они по-разному:
/// новый пароль не проходит политику (её видно до дорогого derive), текущий пароль не тот,
/// файл не удалось перезаписать. Раньше всё это приходило в UI как «текущий пароль неверен» —
/// и пользователь перебирал верный пароль, пока ядро жаловалось на длину нового.
Future<void> vaultChangePassword({required String old, required String new_}) =>
    RustLib.instance.api.crateApiCitadelVaultChangePassword(
      old: old,
      new_: new_,
    );

/// Список профилей (vault должен быть разблокирован).
List<ProfileDto> vaultList() => RustLib.instance.api.crateApiCitadelVaultList();

/// Добавить профиль из `citadel://`-ссылки (валидируется через тот же анти-перебор-гейт, что и
/// живое превью, — иначе «добавить» осталось бы быстрым способом проверять догадки).
/// Не `sync`: гейт спит, а на UI-потоке спать нельзя.
Future<ProfileDto> vaultAdd({required String name, required String uri}) =>
    RustLib.instance.api.crateApiCitadelVaultAdd(name: name, uri: uri);

/// Удалить профиль по id.
void vaultRemove({required String id}) =>
    RustLib.instance.api.crateApiCitadelVaultRemove(id: id);

/// Разобрать `citadel://`-ссылку → превью для UI (валидация при вставке).
///
/// НЕ `sync` и намеренно небыстрая: см. [`guarded_parse_link`] — мгновенный вердикт «распознана /
/// не распознана» на каждый чих клавиатуры был бесплатным оракулом для подбора ссылки.
Future<LinkSummaryDto> parseLinkSummary({required String uri}) =>
    RustLib.instance.api.crateApiCitadelParseLinkSummary(uri: uri);

/// C7.4: QR-матрица `citadel://`-ссылки (экран выдачи доступа абоненту). Sync — кодирование QR
/// дёшево, а ссылка и так уже в Dart-памяти (только что выдана).
QrDto linkQr({required String uri}) =>
    RustLib.instance.api.crateApiCitadelLinkQr(uri: uri);

/// Подключить по «сырой» ссылке (ещё не сохранённой — первый коннект перед сохранением).
Stream<VpnEventDto> vpnConnect({required String link}) =>
    RustLib.instance.api.crateApiCitadelVpnConnect(link: link);

/// Подключить по сохранённому профилю (ссылка достаётся из vault, не покидает ядро).
Stream<VpnEventDto> vpnConnectProfile({required String id}) =>
    RustLib.instance.api.crateApiCitadelVpnConnectProfile(id: id);

/// Android: старт нативной сессии (сырая ссылка). Останов — [`android_stop_session`].
Stream<VpnEventDto> androidStartSession({required String link}) =>
    RustLib.instance.api.crateApiCitadelAndroidStartSession(link: link);

/// Android: старт нативной сессии по сохранённому профилю (ссылка не покидает ядро).
Stream<VpnEventDto> androidStartSessionProfile({required String id}) =>
    RustLib.instance.api.crateApiCitadelAndroidStartSessionProfile(id: id);

/// Android: снимок статуса сессии (sync) — перезапуск (новый изолят) спрашивает при старте, чтобы
/// отразить живой VPN, а не показать «отключено» и не поднять второй коннект поверх (нюанс 2).
AndroidStatusDto androidSessionStatus() =>
    RustLib.instance.api.crateApiCitadelAndroidSessionStatus();

/// Android: переподписать новый Dart-изолят на события живой сессии (перезапуск после закрытия окна).
/// Ставит `sink` текущим (перекрывает мёртвый) и сразу праймит его снимком (state + connected-инфо),
/// чтобы UI-поток был консистентен без ожидания следующего события контроллера.
Stream<VpnEventDto> androidAttachEvents() =>
    RustLib.instance.api.crateApiCitadelAndroidAttachEvents();

/// Android: остановить сессию (пользователь нажал «Отключить»). Глушит нативный loop (реконнект),
/// инкремент [`ANDROID_GEN`] выводит форвард-задачу, статус → idle, sink снят — чтобы перезапуск
/// не принял мёртвую сессию за живую.
void androidStopSession() =>
    RustLib.instance.api.crateApiCitadelAndroidStopSession();

/// Разорвать активную сессию (если есть).
void vpnDisconnect() => RustLib.instance.api.crateApiCitadelVpnDisconnect();

/// Windows: погасить привилегированную службу `citadel-svc` при ВЫХОДЕ из приложения (п.2) —
/// elevated-процесс не должен висеть в задачах, когда клиента нет. Зовётся из Dart последним шагом
/// выхода (после [`vpn_disconnect`], иначе служба занята pump'ом активной сессии и не ответит).
/// На следующем подключении провайдер поднимет службу обратно через SCM. Best-effort: на прочих
/// платформах и при недоступной службе — тихий no-op (выход из приложения не блокируем).
void desktopServiceQuit() =>
    RustLib.instance.api.crateApiCitadelDesktopServiceQuit();

/// Windows: завершить процесс НЕМЕДЛЕННО — последний шаг выхода из приложения.
///
/// Зачем так, а не `windowManager.destroy()`. `destroy()` лишь шлёт `WM_QUIT`: цикл сообщений
/// выходит, а дальше рантайм разбирает движок Flutter, плагины и COM — уже после `CoUninitialize()`
/// в runner'е — пока живы наши нативные потоки (лог-захват stderr, реконнект-воркеры, tokio) и
/// FRB-стримы, которые в этот момент ещё могут постить в гаснущий изолят. Разбор такого хозяйства
/// в правильном порядке нам не нужен: к моменту вызова всё, что должно пережить выход, уже на
/// диске (vault пишется атомарно на каждую операцию), kill-switch снят disconnect'ом, служба
/// уведомлена, иконка трея убрана. Поэтому просто выходим с кодом 0 — это и есть то, что делают
/// десктопные приложения с нативными фоновыми потоками (ср. `TerminateCurrentProcessImmediately`
/// в Chromium), и заодно исчезает окно WER «Программа прекратила работу» на штатном закрытии.
///
/// `TerminateProcess`, а не `ExitProcess`: последний рассылает `DLL_PROCESS_DETACH` уже после
/// остановки остальных потоков — поток, замороженный внутри аллокатора, оставил бы захваченный
/// heap-лок, и detach-обработчик мог бы на нём повиснуть (выход «зависает» вместо мгновенного).
/// На прочих платформах — no-op: там выход и так штатный.
void desktopExitNow() => RustLib.instance.api.crateApiCitadelDesktopExitNow();

/// Прогнать тест-кейсы подключения к exit'у профиля/ссылки, стримя результат по шагам
/// (DNS → QUIC/UDP → TCP → establish → egress). Диагностика идёт тем же путём, что реальный
/// коннект, поэтому показывает, где именно рвётся связь. Не трогает активную сессию.
Stream<DiagLineDto> runDiagnostics({String? profileId, String? link}) => RustLib
    .instance
    .api
    .crateApiCitadelRunDiagnostics(profileId: profileId, link: link);

/// Снимок статуса живой Android-сессии для UI при перезапуске (нюанс 2: натив переживает смерть
/// Activity, Dart — нет). `state`: `idle`|`connecting`|`up`|`migrating`|`down`; `profile_id` — ""
/// если коннект по сырой ссылке.
class AndroidStatusDto {
  final String state;
  final String exit;
  final String transport;
  final String cidr;
  final String profileId;

  const AndroidStatusDto({
    required this.state,
    required this.exit,
    required this.transport,
    required this.cidr,
    required this.profileId,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      exit.hashCode ^
      transport.hashCode ^
      cidr.hashCode ^
      profileId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AndroidStatusDto &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          exit == other.exit &&
          transport == other.transport &&
          cidr == other.cidr &&
          profileId == other.profileId;
}

/// Один шаг прогона диагностики для UI.
class DiagLineDto {
  final String step;
  final bool ok;
  final String detail;

  const DiagLineDto({
    required this.step,
    required this.ok,
    required this.detail,
  });

  @override
  int get hashCode => step.hashCode ^ ok.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiagLineDto &&
          runtimeType == other.runtimeType &&
          step == other.step &&
          ok == other.ok &&
          detail == other.detail;
}

/// Превью разобранной `citadel://`-ссылки (экран добавления профиля).
class LinkSummaryDto {
  final bool valid;
  final String servers;
  final String serverName;
  final String kxSuite;
  final bool hasPin;
  final bool hasPqAuth;
  final bool hasObfs;

  /// C7.4: мастер-ссылка (admin) — UI предупреждает: такую нельзя раздавать абонентам.
  final bool isAdmin;

  const LinkSummaryDto({
    required this.valid,
    required this.servers,
    required this.serverName,
    required this.kxSuite,
    required this.hasPin,
    required this.hasPqAuth,
    required this.hasObfs,
    required this.isAdmin,
  });

  static Future<LinkSummaryDto> default_() =>
      RustLib.instance.api.crateApiCitadelLinkSummaryDtoDefault();

  @override
  int get hashCode =>
      valid.hashCode ^
      servers.hashCode ^
      serverName.hashCode ^
      kxSuite.hashCode ^
      hasPin.hashCode ^
      hasPqAuth.hashCode ^
      hasObfs.hashCode ^
      isAdmin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinkSummaryDto &&
          runtimeType == other.runtimeType &&
          valid == other.valid &&
          servers == other.servers &&
          serverName == other.serverName &&
          kxSuite == other.kxSuite &&
          hasPin == other.hasPin &&
          hasPqAuth == other.hasPqAuth &&
          hasObfs == other.hasObfs &&
          isAdmin == other.isAdmin;
}

/// Профиль из хранилища (без секретов — только метаданные для списка/карточки).
class ProfileDto {
  final String id;
  final String name;
  final String servers;
  final bool hasPin;
  final bool hasPqAuth;
  final bool hasObfs;

  /// C7.4: мастер-профиль (ссылка несёт admin_seed) — UI показывает пункт «Абоненты».
  final bool isAdmin;
  final String lastExit;

  const ProfileDto({
    required this.id,
    required this.name,
    required this.servers,
    required this.hasPin,
    required this.hasPqAuth,
    required this.hasObfs,
    required this.isAdmin,
    required this.lastExit,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      servers.hashCode ^
      hasPin.hashCode ^
      hasPqAuth.hashCode ^
      hasObfs.hashCode ^
      isAdmin.hashCode ^
      lastExit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          servers == other.servers &&
          hasPin == other.hasPin &&
          hasPqAuth == other.hasPqAuth &&
          hasObfs == other.hasObfs &&
          isAdmin == other.isAdmin &&
          lastExit == other.lastExit;
}

/// C7.4: QR-код ссылки как битовая матрица `size × size` (1 = тёмный модуль) — рендер в UI
/// кастомным painter'ом, без SVG-зависимости на Dart-стороне.
class QrDto {
  final int size;
  final Uint8List cells;

  const QrDto({required this.size, required this.cells});

  @override
  int get hashCode => size.hashCode ^ cells.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrDto &&
          runtimeType == other.runtimeType &&
          size == other.size &&
          cells == other.cells;
}

/// Плоское DTO split-настройки для FFI. `*_mode` = "off"|"include"|"exclude".
class SplitTunnelDto {
  final String appMode;
  final List<String> apps;
  final String destMode;
  final List<String> dests;

  const SplitTunnelDto({
    required this.appMode,
    required this.apps,
    required this.destMode,
    required this.dests,
  });

  @override
  int get hashCode =>
      appMode.hashCode ^ apps.hashCode ^ destMode.hashCode ^ dests.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SplitTunnelDto &&
          runtimeType == other.runtimeType &&
          appMode == other.appMode &&
          apps == other.apps &&
          destMode == other.destMode &&
          dests == other.dests;
}

/// Событие VPN-сессии для UI. `kind`: `state` | `connected` | `error`.
class VpnEventDto {
  final String kind;

  /// Для `kind=state`: `idle`|`connecting`|`up`|`migrating`|`down`.
  final String state;

  /// Для `kind=connected`: выбранный exit, транспорт, адрес (CIDR).
  final String exit;
  final String transport;
  final String cidr;

  /// Для `kind=error`: текст ошибки.
  final String error;

  const VpnEventDto({
    required this.kind,
    required this.state,
    required this.exit,
    required this.transport,
    required this.cidr,
    required this.error,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      state.hashCode ^
      exit.hashCode ^
      transport.hashCode ^
      cidr.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VpnEventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          state == other.state &&
          exit == other.exit &&
          transport == other.transport &&
          cidr == other.cidr &&
          error == other.error;
}
