// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `profile_to_dto`, `rt`, `start_connect`, `to_dto`, `vault_path`

/// Версия PQ-VPN-ядра (about-экран).
String coreVersion() => RustLib.instance.api.crateApiCitadelCoreVersion();

/// Существует ли файл хранилища (UI: разблокировать vs первый запуск).
bool vaultExists() => RustLib.instance.api.crateApiCitadelVaultExists();

/// Разблокирован ли vault в текущей сессии приложения.
bool vaultIsUnlocked() => RustLib.instance.api.crateApiCitadelVaultIsUnlocked();

/// Заблокировать (забыть ключ из памяти).
void vaultLock() => RustLib.instance.api.crateApiCitadelVaultLock();

/// Открыть хранилище мастер-паролем (PBKDF2 — намеренно НЕ sync: тяжело, уводим с UI-потока).
Future<void> vaultUnlock({required String passphrase}) =>
    RustLib.instance.api.crateApiCitadelVaultUnlock(passphrase: passphrase);

/// Создать новое хранилище под мастер-паролем (первый запуск / первое сохранение).
Future<void> vaultCreate({required String passphrase}) =>
    RustLib.instance.api.crateApiCitadelVaultCreate(passphrase: passphrase);

/// Сменить мастер-пароль (текущий проверяется повторным open).
Future<void> vaultChangePassword({required String old, required String new_}) =>
    RustLib.instance.api.crateApiCitadelVaultChangePassword(
      old: old,
      new_: new_,
    );

/// Список профилей (vault должен быть разблокирован).
List<ProfileDto> vaultList() => RustLib.instance.api.crateApiCitadelVaultList();

/// Добавить профиль из `citadel://`-ссылки (валидируется).
ProfileDto vaultAdd({required String name, required String uri}) =>
    RustLib.instance.api.crateApiCitadelVaultAdd(name: name, uri: uri);

/// Удалить профиль по id.
void vaultRemove({required String id}) =>
    RustLib.instance.api.crateApiCitadelVaultRemove(id: id);

/// Разобрать `citadel://`-ссылку → превью для UI (живая валидация при вставке).
LinkSummaryDto parseLinkSummary({required String uri}) =>
    RustLib.instance.api.crateApiCitadelParseLinkSummary(uri: uri);

/// Подключить по «сырой» ссылке (ещё не сохранённой — первый коннект перед сохранением).
Stream<VpnEventDto> vpnConnect({required String link}) =>
    RustLib.instance.api.crateApiCitadelVpnConnect(link: link);

/// Подключить по сохранённому профилю (ссылка достаётся из vault, не покидает ядро).
Stream<VpnEventDto> vpnConnectProfile({required String id}) =>
    RustLib.instance.api.crateApiCitadelVpnConnectProfile(id: id);

/// Разорвать активную сессию (если есть).
void vpnDisconnect() => RustLib.instance.api.crateApiCitadelVpnDisconnect();

/// Превью разобранной `citadel://`-ссылки (экран добавления профиля).
class LinkSummaryDto {
  final bool valid;
  final String servers;
  final String serverName;
  final String kxSuite;
  final bool hasPin;
  final bool hasPqAuth;
  final bool hasObfs;

  const LinkSummaryDto({
    required this.valid,
    required this.servers,
    required this.serverName,
    required this.kxSuite,
    required this.hasPin,
    required this.hasPqAuth,
    required this.hasObfs,
  });

  static Future<LinkSummaryDto> default_() =>
      RustLib.instance.api.crateApiCitadelLinkSummaryDtoDefault();

  @override
  int get hashCode =>
      valid.hashCode ^
      servers.hashCode ^
      serverName.hashCode ^
      kxSuite.hashCode ^
      hasPin.hashCode ^
      hasPqAuth.hashCode ^
      hasObfs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinkSummaryDto &&
          runtimeType == other.runtimeType &&
          valid == other.valid &&
          servers == other.servers &&
          serverName == other.serverName &&
          kxSuite == other.kxSuite &&
          hasPin == other.hasPin &&
          hasPqAuth == other.hasPqAuth &&
          hasObfs == other.hasObfs;
}

/// Профиль из хранилища (без секретов — только метаданные для списка/карточки).
class ProfileDto {
  final String id;
  final String name;
  final String servers;
  final bool hasPin;
  final bool hasPqAuth;
  final bool hasObfs;
  final String lastExit;

  const ProfileDto({
    required this.id,
    required this.name,
    required this.servers,
    required this.hasPin,
    required this.hasPqAuth,
    required this.hasObfs,
    required this.lastExit,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      servers.hashCode ^
      hasPin.hashCode ^
      hasPqAuth.hashCode ^
      hasObfs.hashCode ^
      lastExit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          servers == other.servers &&
          hasPin == other.hasPin &&
          hasPqAuth == other.hasPqAuth &&
          hasObfs == other.hasObfs &&
          lastExit == other.lastExit;
}

/// Событие VPN-сессии для UI. `kind`: `state` | `connected` | `error`.
class VpnEventDto {
  final String kind;

  /// Для `kind=state`: `idle`|`connecting`|`up`|`migrating`|`down`.
  final String state;

  /// Для `kind=connected`: выбранный exit, транспорт, адрес (CIDR).
  final String exit;
  final String transport;
  final String cidr;

  /// Для `kind=error`: текст ошибки.
  final String error;

  const VpnEventDto({
    required this.kind,
    required this.state,
    required this.exit,
    required this.transport,
    required this.cidr,
    required this.error,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      state.hashCode ^
      exit.hashCode ^
      transport.hashCode ^
      cidr.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VpnEventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          state == other.state &&
          exit == other.exit &&
          transport == other.transport &&
          cidr == other.cidr &&
          error == other.error;
}
