// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bus`, `load_prev_log_history`, `push_line_mem`, `push_line`, `spawn_stderr_capture`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LogBus`

/// Задать путь файла-персиста лога. NB (S1.4/M8): сам файловый персист по умолчанию ВЫКЛЮЧЕН
/// (приватность — лог несёт серверы/адреса/время); файл пишется ТОЛЬКО при `Citadel_DEBUG_LOG`,
/// иначе лог живёт лишь в in-memory ring. Путь задаётся заранее, чтобы дебаг-режим знал, куда писать.
void setLogFile({required String path}) =>
    RustLib.instance.api.crateApiDiagSetLogFile(path: path);

/// Один раз подменить stderr на pipe и начать раздачу строк в UI. Идемпотентно; зовётся из
/// `main.dart` сразу после `RustLib.init()`. Unix — dup2(fd 2); Windows — SetStdHandle(STDERR).
/// На прочих ОС — no-op.
void startLogCapture() => RustLib.instance.api.crateApiDiagStartLogCapture();

/// Живой хвост логов: подписка на новые строки (после `start_log_capture`). Отдаётся Dart'у
/// как `Stream<String>`. Крутится в отдельном потоке (broadcast::blocking_recv), рвётся когда
/// Dart отписался.
Stream<String> debugLogStream() =>
    RustLib.instance.api.crateApiDiagDebugLogStream();

/// Снимок кольцевого буфера (история — для прайминга панели и «Копировать»).
List<String> debugLogSnapshot() =>
    RustLib.instance.api.crateApiDiagDebugLogSnapshot();

/// Очистить историю логов.
void debugLogClear() => RustLib.instance.api.crateApiDiagDebugLogClear();
